import { useEffect, useRef, useState } from "react";

// Playful, non-literal copy shown while a tailoring run is in flight. Deliberately
// NOT the real pipeline stage names — the progress bar (driven by the server's
// real 0-100 progress) already carries the honest signal; this is just voice,
// so users feel the AI is alive and working rather than staring at a dead spinner.
export const TAILOR_FLAVOR: string[] = [
  "Spazoozling your bullet points…",
  "Making you the best you can be…",
  "Polishing verbs till they gleam…",
  "Consulting the résumé oracle…",
  "Untangling your career story…",
  "Hunting for hidden superpowers…",
  "Sweet-talking the applicant tracking system…",
  "Buffing your best bullets…",
  "Whittling jargon into clarity…",
  "Aligning your stars (and your skills)…",
  "Teaching your CV to speak recruiter…",
  "Squeezing more \"wow\" per word…",
  "Reticulating splines… on your resume…",
  "Channeling your inner hiring manager…",
  "Cross-referencing the job description…",
  "Matching keywords like a detective…",
  "Giving your achievements a megaphone…",
  "Ironing out the wrinkles…",
  "Sharpening pencils and pitches…",
  "Fetching your finest accomplishments…",
  "Tightening loose sentences…",
  "Distilling your career into gold…",
  "Rehearsing your elevator pitch…",
  "Fluffing up your skill pillows…",
  "Convincing robots you're hireable…",
  "Optimizing for maximum impressiveness…",
  "Weaving your experience into a narrative…",
  "Consulting the ghost of resumes past…",
  "Untangling buzzword spaghetti…",
  "Sprinkling in some star power…",
  "Rebuilding your bullets, brick by brick…",
  "Zhuzhing your job titles…",
  "Doing the recruiter's homework for them…",
  "Calibrating your confidence levels…",
  "Assembling your greatest hits…",
  "Making your summary sing…",
  "Translating \"career\" into \"compelling\"…",
  "Fine-tuning your professional frequency…",
  "Summoning the perfect adjective…",
  "Cross-checking against the job post…",
  "Shining a spotlight on your wins…",
  "Trimming the fat, keeping the muscle…",
  "Turning tasks into triumphs…",
  "Reorganizing your résumé's feng shui…",
  "Whisking your work history into shape…",
  "Percolating fresh phrasing…",
  "Auditing your accomplishments…",
  "Priming the pump on your pitch…",
  "Wrangling wayward commas…",
  "Coaxing out quantifiable wins…",
  "Consulting the recruiter crystal ball…",
  "Adding a dash of gravitas…",
  "Recalibrating your resume's radar…",
  "Simmering your story down to essentials…",
  "Making buzzwords behave…",
  "Choreographing your career highlights…",
  "Reading between the job description's lines…",
  "Turning \"did stuff\" into \"delivered results\"…",
  "Spitshining your skills section…",
  "Doing a little résumé alchemy…",
  "Curating your career's greatest arc…",
  "Fetching the perfect verb…",
  "Reconciling ambition with evidence…",
  "Making sure the ATS falls in love…",
  "Tuning your tone to \"hire me\"…",
  "Assembling proof of your genius…",
  "Refactoring your resume's logic…",
  "Sanding down rough edges…",
  "Bottling your work ethic…",
  "Cataloging your career wins…",
  "Reweaving résumé threads…",
  "Consulting the muses of LinkedIn…",
  "Prepping your paragraphs for battle…",
  "Sorting skills from strongest to strongest…",
  "Adding some professional swagger…",
  "Turning experience into evidence…",
  "Loading extra confidence into your bullets…",
  "Aligning stars, skills, and syntax…",
  "Reverse-engineering the job posting…",
  "Massaging your metrics into shape…",
  "Debugging your career narrative…",
  "Spinning straw into resume gold…",
  "Sharpening your competitive edge…",
  "Decluttering your career closet…",
  "Making every word earn its keep…",
  "Synchronizing skills with requirements…",
  "Prepping your best foot forward…",
  "Concocting the perfect summary…",
  "Coaching your bullets to be bolder…",
  "Untangling the résumé knot…",
  "Rolling out the professional red carpet…",
  "Perfecting your paper handshake…",
  "Consulting the hiring gods…",
  "Distilling ten years into ten lines…",
  "Recasting your role as the hero…",
  "Buffing your bragging rights…",
  "Charging up your career highlights…",
  "Composing your professional symphony…",
  "Reticulating résumé splines…",
  "Turning modesty into metrics…",
  "Baking your bullets to perfection…",
  "Prepping your paperwork for prime time…",
  "Sifting for standout achievements…",
  "Cross-training your career story…",
  "Massaging metaphors into meaning…",
  "Warming up your work history…",
  "Sprucing up your skill set…",
  "Recharging your résumé's batteries…",
  "Stirring the pot of possibility…",
  "Squinting at the job description again…",
  "Untying jargon knots…",
  "Bringing your CV up to code…",
  "Rewriting history (the good parts)…",
  "Prepping a highlight reel of you…",
  "Practicing your professional poker face…",
  "Compiling your career's director's cut…",
  "Aligning your resume's chakras…",
  "Detecting hidden strengths…",
  "Applying a fresh coat of polish…",
  "Reformatting your ambition…",
  "Wrangling weasel words into submission…",
  "Assembling the case for hiring you…",
  "Cooking up a killer summary…",
  "Turning \"responsible for\" into \"delivered\"…",
  "Extracting maximum signal, minimum noise…",
  "Sculpting your story into shape…",
  "Sending your skills to finishing school…",
  "Consulting the résumé style guide…",
  "Rehydrating dry job descriptions…",
  "Reworking your résumé's rhythm…",
  "Prepping talking points for the interview…",
  "Injecting a little extra ambition…",
  "Making the recruiter's job easy…",
  "Locking in your best angle…",
  "Reticulating your relevant experience…",
  "Whisking away the filler words…",
  "Bench-pressing your bullet points…",
  "Convincing the algorithm you're the one…",
  "Stitching your story into a strong narrative…",
  "Fine-combing for forgotten wins…",
  "Prepping your professional glow-up…",
  "Buffering your best qualities…",
  "Getting your résumé interview-ready…",
  "Refining your résumé's recipe…",
  "Turning \"helped with\" into \"led\"…",
  "Consulting the ancient scrolls of recruiting…",
  "Making your resume ATS-fluent…",
  "Assembling your professional highlight reel…",
  "Double-checking your greatest hits…",
  "Tuning up your talking points…",
  "Adding some extra sparkle…",
  "Prepping your paper trail of proof…",
  "Reweighing your resume's priorities…",
  "Bringing precision to your pitch…",
  "Charging your CV with confidence…",
  "Reading the job post one more time…",
  "Matching your muscle memory to the mission…",
  "Turning your track record into a trailer…",
  "Optimizing your one-page masterpiece…",
  "Reticulating relevant requirements…",
  "Prepping your professional highlight tape…",
  "Making the case, bullet by bullet…",
  "Buffing out any awkward phrasing…",
  "Choosing words that pull their weight…",
  "Coordinating skills with the scoreboard…",
  "Prepping the perfect first impression…",
  "Recasting routine work as remarkable…",
  "Getting your résumé recruiter-ready…",
  "Aligning ambition with the job spec…",
  "Cross-referencing your career highlights…",
  "Sprinkling in some strategic keywords…",
  "Prepping your paperwork's best angle…",
  "Making sure every bullet lands…",
  "Turning your CV into a conversation starter…",
  "Reworking rough drafts into results…",
  "Consulting the hiring committee (hypothetically)…",
  "Buffing your professional shine…",
  "Getting the details just right…",
  "Making your resume unmissable…",
  "Squeezing in one more win…",
  "Prepping your pitch for liftoff…",
  "Recomputing your career trajectory…",
  "Making sure nothing gets lost in translation…",
  "Finalizing your professional glow-up…",
  "Buttoning up the last few details…",
  "Running one more pass for polish…",
  "Tightening the final bolts…",
  "Wrapping up your resume's best version yet…"
];

// Shuffle-bag cycling so a stacked set of run cards never shows the same
// phrase twice in a row, and different cards (seeded differently) diverge.
export function useTailorFlavor(active: boolean, seed = 0, intervalMs = 3000): string {
  const orderRef = useRef<number[]>([]);
  const posRef = useRef(0);
  const [phrase, setPhrase] = useState(() => TAILOR_FLAVOR[seed % TAILOR_FLAVOR.length] ?? TAILOR_FLAVOR[0]!);

  useEffect(() => {
    if (!active) return;
    function reshuffle() {
      const order = TAILOR_FLAVOR.map((_, i) => i);
      for (let i = order.length - 1; i > 0; i -= 1) {
        const j = Math.floor(Math.random() * (i + 1));
        [order[i], order[j]] = [order[j]!, order[i]!];
      }
      orderRef.current = order;
      posRef.current = 0;
    }
    reshuffle();
    // Start each card on a different phrase so a stack of 3 doesn't read identically.
    setPhrase(TAILOR_FLAVOR[(seed * 37) % TAILOR_FLAVOR.length] ?? TAILOR_FLAVOR[0]!);
    const timer = setInterval(() => {
      posRef.current += 1;
      if (posRef.current >= orderRef.current.length) reshuffle();
      const next = orderRef.current[posRef.current];
      setPhrase(TAILOR_FLAVOR[next ?? 0] ?? TAILOR_FLAVOR[0]!);
    }, intervalMs);
    return () => clearInterval(timer);
  }, [active, seed, intervalMs]);

  return phrase;
}
